[rust]
edition = "2021"   #在线运行用2021版本的

[book]
authors = ["sunface"]
language = "zh-CN"
title = "Rust语言圣经(Rust Course)"
src = "src"

[output.html]
additional-css = ["theme/style.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/sunface/rust-course"
edit-url-template = "https://github.com/sunface/rust-course/edit/main/{path}"
site-url = "https://course.rs/"

[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 0

[output.pandoc]
disabled = false

[output.pandoc.profile.pdf]
output-file = "rust-course.pdf"
pdf-engine = "tectonic"
pdf-engine-opt = ["-k"]
to = "pdf"
variables = { mainfont = "Noto Sans CJK SC", sansfont = "Noto Sans CJK SC", CJKmainfont = "Noto Sans CJK SC" }

[output.pandoc.profile.epub]
output-file = "rust-course.epub"
to = "epub3"
